=== kenydebo/Practice/xml/day1/Afternoon/city2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT city (quadrant+)>
	<!ATTLIST city name CDATA #REQUIRED>	<!-- CDATA meaning that data is required -->
	
<!ELEMENT quadrant (community+)>
	<!ATTLIST quadrant name (NW|NE|SE|SW) #REQUIRED
								 size CDATA #IMPLIED>

<!ELEMENT community (#PCDATA)>

=== kenydebo/Practice/xml/day1/Afternoon/city2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE city SYSTEM "city2.dtd">
<city name="Calgary">
	<quadrant name="NW">
		<community>Arbour Lake</community>
	</quadrant>
	<quadrant name="NE" size="1234">
		<community>Saddle Ridge</community>
	</quadrant>
	<quadrant name="SW">
		<community>Mardaloop</community>
	</quadrant>
	<quadrant name="SE">
		<community>McKenzie Town</community>
	</quadrant>
</city>
